export { repairSync, syncNow, type SyncNowOptions } from './sync-now'
export { findReviewItems } from './find-review-items'
export { describeReviewItems } from './describe-review-items'
export { applyPendingDeletions } from './apply-pending-deletions'
export { noteCloudChange } from './note-cloud-change'
export { createPendingChangePort } from './create-pending-change-port'
export type { SyncDeps } from './sync-deps'
