/** Canonical route paths. The router (app/) and any navigation read from here. */
export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  forgot: '/forgot',
  welcome: '/welcome',
  palaces: '/palaces',
  palaceDetail: '/palaces/$palaceId',
  palaceSettings: '/palaces/$palaceId/settings',
  palaceStudy: '/palaces/$palaceId/study',
  palacePractice: '/palaces/$palaceId/practice',
  palaceMatch: '/palaces/$palaceId/match',
  palaceQuiz: '/palaces/$palaceId/quiz',
  roomHub: '/rooms/$roomId',
  roomSettings: '/rooms/$roomId/settings',
  roomCardNew: '/rooms/$roomId/cards/new',
  roomCardEdit: '/rooms/$roomId/cards/$cardId',
  roomPaste: '/rooms/$roomId/paste',
  roomImport: '/rooms/$roomId/import',
  roomQuestions: '/rooms/$roomId/questions',
  roomQuestionNew: '/rooms/$roomId/questions/new',
  roomQuestionEdit: '/rooms/$roomId/questions/$questionId',
  roomStudy: '/rooms/$roomId/study',
  roomPractice: '/rooms/$roomId/practice',
  roomMatch: '/rooms/$roomId/match',
  roomQuiz: '/rooms/$roomId/quiz',
  profile: '/profile',
  streak: '/streak',
  badges: '/badges',
  badgeDetail: '/badges/$badgeId',
  achievements: '/achievements',
  achievementDetail: '/achievements/$achievementId',
  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsChangePassword: '/settings/change-password',
  settingsPrivacy: '/settings/privacy',
  settingsSwipe: '/settings/swipe',
  settingsClear: '/settings/clear-data',
  settingsHelp: '/settings/help',
  settingsAbout: '/settings/about',
  notifications: '/notifications',
} as const

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES]
