/** Canonical route paths. The router (app/) and any navigation read from here. */
export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  forgot: '/forgot',
  welcome: '/welcome',
  palaces: '/palaces',
  palaceDetail: '/palaces/$palaceId',
  palaceQuiz: '/palaces/$palaceId/quiz',
  roomContent: '/rooms/$roomId',
  roomTrain: '/rooms/$roomId/train',
  roomMatch: '/rooms/$roomId/match',
  roomVerse: '/rooms/$roomId/verse',
  review: '/review',
  profile: '/profile',
  streak: '/streak',
  badges: '/badges',
  badgeDetail: '/badges/$badgeId',
  achievements: '/achievements',
  achievementDetail: '/achievements/$achievementId',
  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsChangePassword: '/settings/change-password',
  settingsPrivacy: '/settings/privacy',
  settingsHelp: '/settings/help',
  settingsAbout: '/settings/about',
  notifications: '/notifications',
} as const

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES]
