export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  forgot: '/forgot',
  welcome: '/welcome',
  deckDetail: '/decks/:deckId',
  deckSettings: '/decks/:deckId/settings',
  deckStudy: '/decks/:deckId/study',
  deckMatch: '/decks/:deckId/match',
  deckQuiz: '/decks/:deckId/quiz',
  deckCardNew: '/decks/:deckId/cards/new',
  deckCardEdit: '/decks/:deckId/cards/:cardId',
  deckPaste: '/decks/:deckId/paste',
  deckImport: '/decks/:deckId/import',
  newPaste: '/import/paste',
  deckQuestions: '/decks/:deckId/questions',
  deckQuestionNew: '/decks/:deckId/questions/new',
  deckQuestionEdit: '/decks/:deckId/questions/:questionId',
  archived: '/archived',
  profile: '/profile',
  streak: '/streak',
  badges: '/badges',
  badgeDetail: '/badges/:badgeId',
  achievements: '/achievements',
  achievementDetail: '/achievements/:achievementId',
  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsChangePassword: '/settings/change-password',
  settingsPrivacy: '/settings/privacy',
  settingsSwipe: '/settings/swipe',
  settingsSelect: '/settings/select-toolbar',
  settingsHelp: '/settings/help',
  settingsAbout: '/settings/about',
  notifications: '/notifications',
} as const

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES]
